server:
  port: 8769
spring:
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/    
zuul:
  prefix: /api
  routes:
    work:
      path: /work/**
      serviceId: craft-work-server
    employ:
      path: /employ/**
      serviceId: craft-employ-server
  retryable: true
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0