server:
  port: 8769
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/    
zuul:
  prefix: /api
  routes:
    admin:
      path: /admin/**
      serviceId: craft-admin-server
    web:
      path: /web/**
      serviceId: craft-web-server
    work:
      path: /work/**
      serviceId: craft-work-server
    employ:
      path: /employ/**
      serviceId: craft-employ-server
  retryable: true
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0
#日志
logging:
  config: classpath:logback-boot.xml