server:
  port: 8768
spring:
  application:
    name: craft-search-server
  data:
    elasticsearch:
      cluster-name: my-elasticsearch #默认即为 elasticsearch
      cluster-nodes: pee1:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      properties:
        path:
          logs: ./elasticsearch/log #elasticsearch日志存储目录
          data: ./elasticsearch/data #elasticsearch数据存储目录
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/

  